# Base configs
baseurl: "https://idiotidiotidiot.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/fulls"
google_analytics: "UA-46465113-2"

# UI configs
title: "Faiza is an idiot"
subtitle: "See how big of an idiot Faiza is!"
author: "Bilal"
header:
 title: "Why Faiza is an Idiot"
 subtitle: "idiotidiotidiot.com"
footer:
 name: "This website is dedicated to explaining why Faiza is Dumb"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
